version: 2
jobs:
  build:
    working_directory: ~/AndroidDemo
    docker:
    - image: circleci/android:api-27-alpha
    environment:
      _JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    #      - run:
    #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
    #         command: sudo chmod +x ./gradlew
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Setup Emulator
        command: sdkmanager "system-images;android-23;google_apis;x86"


  - run:
      name: Setup Emulator 2
      command: savdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"

    - run:
        name: Run Emulator
        command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
        background: true

    - run:
        name: Run Tests
        command: ./gradlew lint test

    - run:
        name: waiting for system to boot
        command: circle-android wait-for-boot

    - run:
        name: Run Instrument Tests MyTaxi
        command:  ./gradlew connectedAndroidTest --stacktrace


    - store_artifacts:
        path: app/build/reports
        destination: reports
    - store_test_results:
        path: app/build/test-results
